CREATE TABLE INSPEKTORI (
ID INT IDENTITY PRIMARY KEY NOT NULL,
IME VARCHAR(50) NOT NULL UNIQUE,
CHECK LENGTH(IME) > 0
);

CREATE TABLE SPECIALNOSTI ( 
ID INT IDENTITY PRIMARY KEY NOT NULL, 
SPECIALNOST VARCHAR(50) NOT NULL UNIQUE, 
    CHECK LENGTH(SPECIALNOST) > 0, 
INSPEKTOR_ID INT NOT NULL, 
FOREIGN KEY (INSPEKTOR_ID) REFERENCES INSPEKTORI(ID) ON DELETE CASCADE
);

CREATE TABLE STUDENTI ( 
ID INT IDENTITY PRIMARY KEY NOT NULL, 
FN VARCHAR(10) NOT NULL UNIQUE, 
    CHECK LENGTH(FN) = 10, 
IME VARCHAR(25) NOT NULL, 
    CHECK LENGTH(IME) > 0,
FAMILIQ VARCHAR(25) NOT NULL, 
    CHECK LENGTH(FAMILIQ) >0,
TEL VARCHAR(10) NOT NULL UNIQUE, 
    CHECK LENGTH(TEL) = 10, 
ADDRESS VARCHAR(50), 
SPECIALNOST_ID INT NOT NULL, 
FOREIGN KEY (SPECIALNOST_ID) REFERENCES SPECIALNOSTI(ID) ON DELETE CASCADE
);

CREATE TABLE PREDMETI (
ID INT IDENTITY PRIMARY KEY NOT NULL,
PREDMET VARCHAR(50) NOT NULL,
CHECK LENGTH(PREDMET) > 0,
SPECIALNOST_ID INT NOT NULL,
FOREIGN KEY (SPECIALNOST_ID) REFERENCES SPECIALNOSTI(ID) ON DELETE CASCADE,
UNIQUE KEY PREDMET (SPECIALNOST_ID, PREDMET)
);

CREATE TABLE OCENKI (
ID INT IDENTITY PRIMARY KEY NOT NULL,
STUDENT_ID INT NOT NULL,
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTI(ID) ON DELETE CASCADE,
PREDMET_ID INT NOT NULL,
    FOREIGN KEY (PREDMET_ID) REFERENCES PREDMETI(ID) ON DELETE CASCADE,

SPECIALNOST_ID INT NOT NULL,
    FOREIGN KEY (SPECIALNOST_ID) REFERENCES SPECIALNOSTI(ID) ON DELETE CASCADE,

OCENKA TINYINT NOT NULL,
    CHECK (OCENKA>=2 AND OCENKA<=6),
UNIQUE KEY OCENKA (STUDENT_ID, PREDMET_ID)
);

